/**
 * Style Dictionary v4 build script — DTCG tokens → CSS + TypeScript
 *
 * Uses SD v4 programmatic API with usesDtcg for W3C Design Token parsing.
 * Custom formatters output:
 *   dist/theme.css   — @theme inline + :root (light) + .dark
 *   dist/tokens.ts   — TypeScript constants with type helpers
 */

import StyleDictionary from "style-dictionary";
import type {
  TransformedToken,
  FormatFnArguments,
} from "style-dictionary/types";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Get the resolved value from a token, handling SD v4's $value */
function tokenValue(token: TransformedToken): string {
  const val = token.$value ?? token.value;
  if (Array.isArray(val)) {
    return val.map((v: string) => `"${v}"`).join(", ");
  }
  return String(val);
}

/** Check if a token path starts with a prefix */
function pathStartsWith(token: TransformedToken, ...prefix: string[]): boolean {
  return prefix.every((p, i) => token.path[i] === p);
}

/** Get the last segment of a token's path */
function tokenName(token: TransformedToken): string {
  return token.path[token.path.length - 1];
}

/** Get a dash-joined path excluding given prefix segments */
function tokenNameFrom(token: TransformedToken, from: number): string {
  return token.path.slice(from).join("-");
}

// ---------------------------------------------------------------------------
// Custom Formats
// ---------------------------------------------------------------------------

/** CSS format: @theme inline { } + :root { } + .dark { } */
function formatThemeCSS({ dictionary }: FormatFnArguments): string {
  const allTokens = dictionary.allTokens;
  const lines: string[] = [];

  // Semantic token names that map to --color-* in @theme inline
  const semanticNames: string[] = [];
  const lightTokens = allTokens.filter((t) => pathStartsWith(t, "semantic", "light"));
  for (const t of lightTokens) {
    semanticNames.push(tokenNameFrom(t, 2));
  }

  // --- @theme inline ---
  lines.push("@theme inline {");

  // Color semantic vars
  for (const name of semanticNames) {
    lines.push(`  --color-${name}: var(--${name});`);
  }
  lines.push("");

  // Font families
  const fontSans = allTokens.find((t) =>
    pathStartsWith(t, "font", "family", "sans"),
  );
  const fontMono = allTokens.find((t) =>
    pathStartsWith(t, "font", "family", "mono"),
  );
  if (fontSans) lines.push(`  --font-sans: ${tokenValue(fontSans)};`);
  if (fontMono) lines.push(`  --font-mono: ${tokenValue(fontMono)};`);
  lines.push("");

  // Radius
  const radiusTokens = allTokens.filter((t) => pathStartsWith(t, "radius"));
  for (const t of radiusTokens) {
    lines.push(`  --radius-${tokenName(t)}: var(--radius-${tokenName(t)}-value);`);
  }
  lines.push("");

  // Spacing
  const spacingTokens = allTokens.filter((t) => pathStartsWith(t, "spacing"));
  for (const t of spacingTokens) {
    lines.push(`  --spacing-${tokenName(t)}: var(--spacing-${tokenName(t)}-value);`);
  }

  lines.push("}");
  lines.push("");

  // --- :root (light mode) ---
  lines.push(":root {");
  for (const t of lightTokens) {
    const name = tokenNameFrom(t, 2);
    lines.push(`  --${name}: ${tokenValue(t)};`);
  }
  lines.push("");
  for (const t of radiusTokens) {
    lines.push(`  --radius-${tokenName(t)}-value: ${tokenValue(t)};`);
  }
  lines.push("");
  for (const t of spacingTokens) {
    lines.push(`  --spacing-${tokenName(t)}-value: ${tokenValue(t)};`);
  }
  lines.push("}");
  lines.push("");

  // --- .dark ---
  lines.push(".dark {");
  const darkTokens = allTokens.filter((t) => pathStartsWith(t, "semantic", "dark"));
  for (const t of darkTokens) {
    const name = tokenNameFrom(t, 2);
    lines.push(`  --${name}: ${tokenValue(t)};`);
  }
  lines.push("}");
  lines.push("");

  // --- @media (prefers-color-scheme: dark) fallback ---
  // Priority: user override (class) > system preference > fallback dark
  lines.push("@media (prefers-color-scheme: dark) {");
  lines.push("  :root:not(.light) {");
  for (const t of darkTokens) {
    const name = tokenNameFrom(t, 2);
    lines.push(`    --${name}: ${tokenValue(t)};`);
  }
  lines.push("  }");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/** TypeScript format: typed constants with autocomplete support */
function formatTokensTS({ dictionary }: FormatFnArguments): string {
  const allTokens = dictionary.allTokens;
  const lines: string[] = [];

  lines.push("/**");
  lines.push(" * Auto-generated by build-tokens.ts — DO NOT EDIT");
  lines.push(" */");
  lines.push("");

  // --- Color primitives ---
  lines.push("export const color = {");
  for (const group of ["gray", "accent", "destructive"]) {
    const groupTokens = allTokens.filter(
      (t) => pathStartsWith(t, "color", group) && t.path.length === 3,
    );
    if (groupTokens.length === 0) continue;
    lines.push(`  ${group}: {`);
    for (const t of groupTokens) {
      lines.push(`    "${tokenName(t)}": "${tokenValue(t)}",`);
    }
    lines.push("  },");
  }
  const white = allTokens.find((t) => t.path.join(".") === "color.white");
  const black = allTokens.find((t) => t.path.join(".") === "color.black");
  if (white) lines.push(`  white: "${tokenValue(white)}",`);
  if (black) lines.push(`  black: "${tokenValue(black)}",`);
  lines.push("} as const;");
  lines.push("");

  // --- Font ---
  lines.push("export const font = {");
  lines.push("  family: {");
  const fontSans = allTokens.find((t) =>
    pathStartsWith(t, "font", "family", "sans"),
  );
  const fontMono = allTokens.find((t) =>
    pathStartsWith(t, "font", "family", "mono"),
  );
  if (fontSans) {
    const val = fontSans.$value ?? fontSans.value;
    lines.push(`    sans: ${JSON.stringify(val)},`);
  }
  if (fontMono) {
    const val = fontMono.$value ?? fontMono.value;
    lines.push(`    mono: ${JSON.stringify(val)},`);
  }
  lines.push("  },");

  lines.push("  size: {");
  for (const t of allTokens.filter((t) => pathStartsWith(t, "font", "size"))) {
    lines.push(`    "${tokenName(t)}": "${tokenValue(t)}",`);
  }
  lines.push("  },");

  lines.push("  weight: {");
  for (const t of allTokens.filter((t) => pathStartsWith(t, "font", "weight"))) {
    lines.push(`    ${tokenName(t)}: ${tokenValue(t)},`);
  }
  lines.push("  },");

  lines.push("  lineHeight: {");
  for (const t of allTokens.filter((t) =>
    pathStartsWith(t, "font", "lineHeight"),
  )) {
    lines.push(`    ${tokenName(t)}: ${tokenValue(t)},`);
  }
  lines.push("  },");
  lines.push("} as const;");
  lines.push("");

  // --- Spacing ---
  lines.push("export const spacing = {");
  for (const t of allTokens.filter((t) => pathStartsWith(t, "spacing"))) {
    lines.push(`  "${tokenName(t)}": "${tokenValue(t)}",`);
  }
  lines.push("} as const;");
  lines.push("");

  // --- Radius ---
  lines.push("export const radius = {");
  for (const t of allTokens.filter((t) => pathStartsWith(t, "radius"))) {
    lines.push(`  ${tokenName(t)}: "${tokenValue(t)}",`);
  }
  lines.push("} as const;");
  lines.push("");

  // --- Shadow ---
  lines.push("export const shadow = {");
  for (const t of allTokens.filter((t) => pathStartsWith(t, "shadow"))) {
    lines.push(`  ${tokenName(t)}: "${tokenValue(t)}",`);
  }
  lines.push("} as const;");
  lines.push("");

  // --- Semantic (light + dark) ---
  lines.push("export const semantic = {");
  lines.push("  light: {");
  for (const t of allTokens.filter((t) => pathStartsWith(t, "semantic", "light"))) {
    lines.push(`    "${tokenNameFrom(t, 2)}": "${tokenValue(t)}",`);
  }
  lines.push("  },");
  lines.push("  dark: {");
  for (const t of allTokens.filter((t) => pathStartsWith(t, "semantic", "dark"))) {
    lines.push(`    "${tokenNameFrom(t, 2)}": "${tokenValue(t)}",`);
  }
  lines.push("  },");
  lines.push("} as const;");
  lines.push("");

  // --- Type helpers ---
  lines.push("export type ColorScale = keyof typeof color.gray;");
  lines.push("export type AccentScale = keyof typeof color.accent;");
  lines.push("export type SemanticToken = keyof typeof semantic.dark;");
  lines.push("export type SpacingToken = keyof typeof spacing;");
  lines.push("export type RadiusToken = keyof typeof radius;");
  lines.push("export type FontSize = keyof typeof font.size;");
  lines.push("export type FontWeight = keyof typeof font.weight;");
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

async function main() {
  // Register custom formats
  StyleDictionary.registerFormat({
    name: "custom/theme-css",
    format: formatThemeCSS,
  });

  StyleDictionary.registerFormat({
    name: "custom/tokens-ts",
    format: formatTokensTS,
  });

  const sd = new StyleDictionary({
    source: ["src/tokens/*.json"],
    usesDtcg: true,
    log: { verbosity: "verbose" },
    platforms: {
      css: {
        transformGroup: "css",
        buildPath: "dist/",
        files: [
          {
            destination: "theme.css",
            format: "custom/theme-css",
          },
        ],
      },
      ts: {
        transformGroup: "js",
        buildPath: "dist/",
        files: [
          {
            destination: "tokens.ts",
            format: "custom/tokens-ts",
          },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();
  console.log("\n🎨 Token build complete!");
}

main().catch((err) => {
  console.error("❌ Build failed:", err);
  process.exit(1);
});
